export { default as Title } from './title'
export { default as MenuBar } from './menuBar'
export { default as Content } from './content'
export { default as Footer } from './footer'
export { default as Login } from './login'